#!/bin/bash

#check the directory if it exist
if [[ -d contacts ]]; then
  while getopts ":arsdh" opt; do
    case ${opt} in
      a )#add a new contact to the list
        echo ""
        #ask the use to enter the name,phone,email
        read -ep "Enter the name: " name
        read -ep "Enter the phone number: " phone
        read -ep "Enter the email: " email
        read -ep "Enter the address: " address
        #send the output to the contactList
        echo "$name:$phone:$email:$address" >> ./contacts/contactList
        echo ""
        echo "New contact list added"
;;
      r )#remove a contact from the list
        echo ""
        read -ep "Enter the name of the contact you want to remove: " name
        #check the name in the contactList then delete it using the gawk (GNU AWK a built in function)
        gawk -i inplace '!/'$name'/' ./contacts/contactList
        echo "$name is deleted from the contact list"
;;
      s )#ask the user to enter a name to check for specific information
        read -ep "Enter the name: " name
        echo ""
        echo "Please choose an option"
        echo ""
        echo "[p] for phone number"
        echo ""
        echo "[m] for email"
        echo ""
        echo ""[a] for address
        #read the option they choose
        read -ep "Choose an option: " selection
        
        #created a case to display the phone or email
        case $selection in
            p )
              echo ""
              #splits the text file by : then print the phone number
            awk 'BEGIN { FS=":"; print "Phone\n------------------";} /'^$name'/ {print $2;}' ./contacts/contactList;;
            m )
              echo ""
              #splits the text file by : then prints the emamil
             awk 'BEGIN { FS=":"; print "Email\n------------------";} /'^$name'/ {print $3;}' ./contacts/contactList;;
 
            a )
              echo ""
              #splits the test file by : then prints the address
              awk 'BEGIN { FS=":"; print "Address\n------------------";} /'^$name'/ {print $4;}' ./contacts/contactList;;
            * )
               #send an error message if theye enter a wrong option
              echo"Invalid Option: $OPTARG use: [pm]"
              exit 1;;
         esac
         exit 0;;

      d )#format the contact list using awk begin and end
        
        awk 'BEGIN {FS=":"; printf ("%-10s\t%-12s\t%-20s\t%s\n", "Name","Phone Number", "Email","Address") } {printf ("%-10s\t%-12s\t%-20s\t%s\n", $1,$2,$3,$4) }' ./contacts/contactList ;;           
      
      h)    
        echo ""
        echo "Options to Choose"
        echo ""
        echo "[-a] to add a new contact"
        echo ""
        echo "[-r] to remove a contact"
        echo ""
        echo "[-s] to seach for specifict information"
        echo ""
        echo "[-d] to dislpay the formatted contact list"
        echo ""   
        ;;
   
      \? )#send an error message
         echo"Invalid Option: $OPTARG use: [pm]"
         exit 1;;
    esac
    exit 0
    done

#if the user did not provide any options it will send a message to the user
if [[ $OPTIND -eq 1 ]] ; then
    echo "Requires an argument or type [-h] for help to show all the command"
    exit 0; fi
shift $(( OPTIND -1 )) #removes the options that have already been handled 

else
    
    echo ""
    echo "creating a directory for contacts and a file for contactlist ..."
    mkdir contacts && touch ./contacts/contactList
    echo ""
    echo "done"
    echo "restart the program"
    exit 0
    
 fi    
