#!/bin/bash

#check the directory if it exist
if [[ -d contacts ]]; then
  while getopts ":arsd" opt; do
    case ${opt} in
      a )#add a new contact to the list
        echo ""
        #ask the use to enter the name,phone,email
        read -e -p "Enter the name: " name
        read -e -p "Enter the phone number: " phone
        read -e -p "Enter the email: " email
        #send the output to the contactList
        echo "$name:$phone:$email" >> ./contacts/contactList
        echo ""
        echo "New contact list added"
;;
      r )#remove a contact from the list
        echo ""
        read -e -p "Enter the name of the contact you want to remove: " name
        #check the name in the contactList then delete it using the gawk (GNU AWK a built in function)
        gawk -i inplace '!/'$name'/' ./contacts/contactList
        echo "$name is deleted from the contact list"
;;
      s )#ask the user to enter a name to check for specific information
        echo ""
        echo "Please choose an option"
        echo ""
        echo "[p] for phone number"
        echo ""
        echo "[m] for email"
        echo ""
        #read the option they choose
        read -e -p "Choose an option: " selection
        
        #created a case to display the phone or email
        case $selection in
            p )
              echo ""
              #splits the text file by : then print the phone number
            awk 'BEGIN { FS=":"; print "Phone\n------------------\n";} /'^$name'/ {print $2;}' ./contacts/contactList;;
            m )
              echo ""
              #splits the text file by : then prints the emamil
             awk 'BEGIN { FS=":"; print "Email\n------------------\n";} /'^$name'/ {print $3;}' ./contacts/contactList;;
 
            * )
               #send an error message if theye enter a wrong option
              echo"Invalid Option: $OPTARG use: [pm]"
              exit 1;;
         esac
         exit 0;;

      d )#format the contact list using awk begin and end
         awk 'BEGIN { FS=":"; print "Phone\n------------------\n";} /'^$name'/ {print $2;}' ./contacts/contactList ;;

      \? )#send an error message
         echo"Invalid Option: $OPTARG use: [pm]"
         exit 1;;
    esac
    exit 0
    done

#if the user did not provide any options it will send a message to the user
if [[ $OPTIND -eq 1 ]] ; then
    clear
    echo ""
    echo "Please select an option"
    echo ""
    echo "[-a] to add a new contact"
    echo ""
    echo "[-r] to remove a contact"
    echo ""
    echo "[-s] to seach for specifict information"
    echo ""
    echo "[-d] to dislpay the formatted contact list"
    echo ""
    exit 0; fi
shift $(( OPTIND -1 )) #removes the options that have already been handled 
else
    
    echo ""
    echo "creating a directory for contacts and a file for contactlist ..."
    mkdir contacts && touch conatactList
    echo ""
    echo "done"
    echo "restart the program"
    exit 0
    
 fi    
