#!/bin/bash
num=1 
filename="$1"
# used read to read each line of the filename
while read line;do
  echo $num\. $line
  ((num++))
  
done < $filename #redirects the filename to the line in while loop
