#!/bin/bash

#ask the user to enter a name to check for specific information
read -e -p "Enter the name of the contact to check for specific information: " name
echo ""
echo "Options"
echo ""
echo "[p] for phone number"
echo ""
echo "[m] for email"
echo ""
#reads the option they choose
read -e -p "Choose an option: " selection

#created a case to display the phone or email
case $selection in
  p )
    echo "" 
    #splits the text file by : then print the phone number
    awk 'BEGIN { FS=":"; print "Phone\n-----------------\n";} /'^$name'/ {print $2;}' ./contacts/contactList;;

  m )
    echo ""
    #splits the text file by : then print the email
    awk 'BEGIN {FS=":"; print "Email\n-----------------\n";} /'^$name'/ {print $3;}' ./contacts/contactList;;

  * ) 
    #send an error message if they enter a wrong option
    echo "Invalid Option: $OPTARG use: [pm]"
    exit 1
    ;;
esac
exit 0


