#!/bin/bash

read contacts 
modify=$(grep $contacts list)

name=$(echo ${modify}| awk -F "-" '{print $1}')
phone=$(echo ${modify}| awk -F "-" '{print $2}')
mail=$(echo ${modify}| awk -F "-" '{print $3}')

while getopts ":ard" opt; do
  case ${opt} in 
     a) #adds a contact to the list
         
        selection=""
        while [[ ${selection} != "D" ]]; do

        clear
        echo " "
        echo " "
        echo "Select the option to add for the new contact"
        echo " "
        echo "[N]ame"
        echo "[P]hone"
        echo "[M]ail"
        echo " "
        echo "Enter [D] when you are done adding all the information "
        

        read -e -p "Please make your choice" selection

        case ${selection} in 
        N | n) read -e -p "New Name" name;;
        P | p) read -e -p "New Phone" phone;;
        M | m) read -e -p "New Mail" mail;;
  
        D) 
          if [[ $name == "" || $phone == "" || $mail == "" ]]; then
            clear
            echo "Missing information: Name:$name Phone:$phone Mail:$mail"
            echo "file not saved"
            exit 1 
          else
 
            clear
            echo "Finished modifying..."
            echo $name "-" $phone "-" $mail >> contacts
            cat contacts
      
          fi
      ;;
        *) clear; echo "Make a valid selection"; sleep 3;;
        esac

        done
;;        
     \? ) echo "Invalid option: $OPTARG use: -a -r -d" 
      ;;

esac
done  
