#!/bin/bash

#created a variable to store the first argument
url=$1


case "$url" in
  $1)
    shift #removing/shifting the first argument 

  while getopts ":f" opt; do
    case ${opt} in
      f ) #store the output to a file when user enters the flag -f
          target=$OPTARG
          wget -O weblinks "$url" #download the html file from the url provided the store it to the weblinks file
          cat weblinks | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" | sort -u > display
          cat display #displays the output
        exit 0 ;;
           #propmpts a user an error message if they enter different flags
      \? ) echo "Invalid option: $OPTARG use: [-f]" 
        exit 1 ;;
    esac
  done
  
#checks if the user provides any flag if not it will run this code
if [[ $OPTIND -eq 1 ]] ; then 
          wget -O weblinks "$url" #download the html file from the url provided then store it to the weblinks file
          cat weblinks | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" | sort -u; fi #displays the content
shift $((OPTIND -1 )) #removes the options that have already been handled from 
  exit 0;;
esac
